### ISSUE TITLE
How to handle, Sign Out?

### ISSUE THREAD

**Issue by cnaa97** [floydjones1/ExpressTSCognito#1]
Hi, I saw your youtube video and source code.

but I wonder how to handle sidn out with aws-sdk? is there any solution?

**Comment by floydjones1** [comment]
@cnaa97 simplest thing to do is to delete the jwt token from the browser

**Comment by floydjones1** [comment]
@cnaa97 I found this link. You would have to implement it yourself doesnt seem to difficult
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GlobalSignOut.html
